#!/bin/bash

if [[ $1 = '-v' || $1 = '--version' ]]; then
  echo 'Slidy Builder version 2.0.0'
  exit 0
fi

if [[ $1 = '-l' ]]; then
  LOCALCHECK=1
else
  LOCALCHECK=
fi

CACHEDIR=$HOME/.slidy-builder

if [ ! -z $LOCALCHECK ]; then
  mkdir -p $CACHEDIR/slidy/{styles,scripts}
  [ -f $CACHEDIR/slidy/styles/slidy.css ] || \
    wget https://www.w3.org/Talks/Tools/Slidy2/styles/slidy.css \
      -O $CACHEDIR/slidy/styles/slidy.css
  [ -f $CACHEDIR/slidy/scripts/slidy.js ] || \
    wget https://www.w3.org/Talks/Tools/Slidy2/scripts/slidy.js \
      -O $CACHEDIR/slidy/scripts/slidy.js

  [ -f $CACHEDIR/2.5.3.tar.gz ] || \
    wget https://github.com/mathjax/MathJax/archive/2.5.3.tar.gz -O $CACHEDIR/2.5.3.tar.gz
  [ -d $CACHEDIR/MathJax-2.5.3 ] || \
    tar xzf $CACHEDIR/2.5.3.tar.gz -C $CACHEDIR
fi

if [ -z $LOCALCHECK ]; then
  if [[ $1 = '--http' ]]; then
    pandoc -i -t slidy -s --mathjax \
      | sed 's|src="//cdn.mathjax.org|src="https://cdn.mathjax.org|'
  else
    pandoc -i -t slidy -s --mathjax \
      | sed 's|src="//cdn.mathjax.org|src="https://cdn.mathjax.org|' \
      | sed 's|http://www.w3.org/Talks|https://www.w3.org/Talks|'
  fi
else
  pandoc -i -t slidy -s --mathjax -V slidy-url="file://${CACHEDIR}/slidy" \
    | sed "s|//cdn.mathjax.org/mathjax/latest|file://${CACHEDIR}/MathJax-2.5.3|"
fi

echo '<!-- Pandoc version:'
pandoc --version \
  | sed 's/^Default user data directory: .*/Default user data directory: <DELETED>/'
echo '-->'
