#!/bin/bash

HTTPS=1
LOCALCHECK=0

for OPT in "$@"; do
  case "$OPT" in
    '-v'|'--version')
      echo 'Slidy Builder version 2.0.0'
      exit 0
      ;;
    '--http')
      HTTPS=0
      ;;
    '-l')
      LOCALCHECK=1
      ;;
    *)
      ;;
  esac
  shift
done

CACHEDIR=$HOME/.slidy-builder

if [ $LOCALCHECK = 1 ]; then
  mkdir -p $CACHEDIR/slidy/{styles,scripts}
  [ -f $CACHEDIR/slidy/styles/slidy.css ] || \
    wget https://www.w3.org/Talks/Tools/Slidy2/styles/slidy.css \
      -O $CACHEDIR/slidy/styles/slidy.css
  [ -f $CACHEDIR/slidy/scripts/slidy.js ] || \
    wget https://www.w3.org/Talks/Tools/Slidy2/scripts/slidy.js \
      -O $CACHEDIR/slidy/scripts/slidy.js

  MATHJAX_VERSION=2.7.5
  [ -f $CACHEDIR/${MATHJAX_VERSION}.tar.gz ] || \
    wget https://github.com/mathjax/MathJax/archive/${MATHJAX_VERSION}.tar.gz -O $CACHEDIR/${MATHJAX_VERSION}.tar.gz
  [ -d $CACHEDIR/MathJax-${MATHJAX_VERSION} ] || \
    tar xzf $CACHEDIR/${MATHJAX_VERSION}.tar.gz -C $CACHEDIR
fi

if [ $LOCALCHECK = 0 ]; then
  if [ $HTTPS = 0 ]; then
    pandoc -i -t slidy -s --mathjax \
      | sed 's/ class="incremental"//' \
      | sed 's|src="//cdn.mathjax.org|src="https://cdn.mathjax.org|'
  else
    pandoc -i -t slidy -s --mathjax \
      | sed 's/ class="incremental"//' \
      | sed 's|src="//cdn.mathjax.org|src="https://cdn.mathjax.org|' \
      | sed 's|http://www.w3.org/Talks|https://www.w3.org/Talks|'
  fi
else
  pandoc -i -t slidy -s --mathjax -V slidy-url="file://${CACHEDIR}/slidy" \
    | sed "s|//cdn.mathjax.org/mathjax/latest|file://${CACHEDIR}/MathJax-2.5.3|"
fi

echo '<!-- Pandoc version:'
pandoc --version \
  | sed 's/^Default user data directory: .*/Default user data directory: <DELETED>/'
echo '-->'
